#!/usr/bin/env node

var program = require("commander");
var prompt = require('password-prompt');
var read = require('read');

const atcModule = require('./atc_module.js');


program
//.version(package.version)
.option("-n, --username <name>", "adp username")
.option("-t, --entries <times>", "time card entries in JSON")
.option("-s, --salaried", "Salaried Mode")
.option("-d, --debug", "debug")



program.parse(process.argv);

if (!process.argv.slice(2).length) {
  program.outputHelp();
}


if (!(program.entries && program.username)){
  process.exit();
}

read({ prompt: 'Password: ', silent: true }, function(er, p) {
  let atcOpts = {entries: program.entries, salariedMode: program.salaried, debug:program.debug, password:p};
  atcModule.runATC(atcOpts);
})

// prompt('password: ').then(
//   p => {
//     let atcOpts = {entries: program.entries, salariedMode: program.salaried, debug:program.debug, password:p};
//     atcModule.runATC(atcOpts);
//   } 
// );





