#!/usr/bin/env node

var program = require("commander");
var prompt = require('password-prompt');
var read = require('read');
const package = require("./package");

const atcModule = require('./atc_module.js');


program
.option("-n, --username <name>", "adp username")
.option("-j, --entriesJSON <times>", "time card entries in JSON, Ex: [{\"hours\":\"8\",\"projectCode\":\"12345\"}]")
.option("-s, --salaried", "salaried mode")
.option("-d, --debug", "debug")
.version(package.version)

program.on('--help', function(){
  console.log('  Examples:');
  console.log('');
  console.log('     atc -n jsmith@someco -j [{"hours":"8","projectCode","12345"}] -s   ');
  console.log('');
});

program.parse(process.argv);

if (!process.argv.slice(2).length) {
  program.outputHelp();
}


if (!(program.entriesJSON && program.username)){
  process.exit();
}

read({ prompt: 'Password: ', silent: true }, function(er, p) {
  let atcOpts = {entries: program.entriesJSON, salariedMode: program.salaried, debug:program.debug, password:p, username:program.username};
  atcModule.runATC(atcOpts);
})






